export const envSchema = {
  type: 'object',
  required: [
    'PORT',
    'COMPANY_ID',
    'AGENT_ID',
    'REDIS_HOST',
    'REDIS_PASSWORD',
    'REDIS_PORT',
    'NATS_SERVERS',
    'NATS_USERNAME',
    'NATS_PASSWORD',
    'DB_API_URL',
    'TASK_API_URL',
    'TOKEN',
  ],
  properties: {
    PORT: { type: 'number', default: 3000 },
    NODE_ENV: { type: 'string', default: 'development' },
    COMPANY_ID: { type: 'string', default: '' },
    AGENT_ID: { type: 'string', default: '' },
    REDIS_HOST: { type: 'string', default: 'localhost' },
    REDIS_PASSWORD: { type: 'string', default: '' },
    REDIS_PORT: { type: 'number', default: 6379 },
    NATS_SERVERS: { type: 'string', default: 'nats://localhost:4222' },
    NATS_USERNAME: { type: 'string', default: 'admin' },
    NATS_PASSWORD: { type: 'string', default: 'admin' },
    DB_API_URL: { type: 'string', default: 'https://db.daisi.dev' },
    TASK_API_URL: { type: 'string', default: 'https://whatsapp-service.daisi.dev' },
    TAGS: { type: 'string', default: 'v1.0.0' },
    TOKEN: { type: 'string', default: '' },
  },
} as const;
